//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolU_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ClassAnnouncements = new HashSet<ClassAnnouncement>();
            this.ClassAssignments = new HashSet<ClassAssignment>();
            this.ClassAttendances = new HashSet<ClassAttendance>();
            this.StudentClasses = new HashSet<StudentClass>();
        }
    
        public int ClassId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> CoursePreRequisite { get; set; }
        public int ClassProfessorId { get; set; }
        public System.DateTime ClassStartDate { get; set; }
        public System.DateTime ClassEndDate { get; set; }
        public System.TimeSpan ClassStartTime { get; set; }
        public System.TimeSpan ClassEndTime { get; set; }
        public int ClassSemesterId { get; set; }
        public int ClassLocationId { get; set; }
    
        public virtual BuildingRoom BuildingRoom { get; set; }
        public virtual Course Course { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAnnouncement> ClassAnnouncements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAssignment> ClassAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAttendance> ClassAttendances { get; set; }
        public virtual Course Course1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}
