//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolU_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventsId { get; set; }
        public string EventName { get; set; }
        public byte[] EventDescription { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.TimeSpan EventStartTime { get; set; }
        public System.TimeSpan EventEndTime { get; set; }
        public Nullable<int> IntrestedDepartment { get; set; }
        public Nullable<bool> IsSchoolWideEvent { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
