//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolU_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolU_DBEntities : DbContext
    {
        public SchoolU_DBEntities()
            : base("name=SchoolU_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<BuildingRoom> BuildingRooms { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassAnnouncement> ClassAnnouncements { get; set; }
        public virtual DbSet<ClassAssignment> ClassAssignments { get; set; }
        public virtual DbSet<ClassAttendance> ClassAttendances { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<SchoolInfo> SchoolInfoes { get; set; }
        public virtual DbSet<SchoolYear> SchoolYears { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentClass> StudentClasses { get; set; }
        public virtual DbSet<StudentClassGrade> StudentClassGrades { get; set; }
        public virtual DbSet<StudentFinalGrade> StudentFinalGrades { get; set; }
        public virtual DbSet<StudentMajor> StudentMajors { get; set; }
        public virtual DbSet<StudentMinor> StudentMinors { get; set; }
        public virtual DbSet<StudentYear> StudentYears { get; set; }
    }
}
