//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolU_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolInfo
    {
        public int SchoolInfoId { get; set; }
        public string SchoolName { get; set; }
        public byte[] SchoolStreetAddress { get; set; }
        public string SchoolState { get; set; }
        public short SchoolZipCode { get; set; }
        public string SchoolMascotName { get; set; }
        public string SchoolMascotImgLocation { get; set; }
    }
}
