//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolU_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMinor
    {
        public int StudentMinorId { get; set; }
        public int StudentId { get; set; }
        public int MinorId { get; set; }
    
        public virtual Major Major { get; set; }
        public virtual Student Student { get; set; }
    }
}
